### PR TITLE
Compatibility with libgit2 1.8+

### PR DESCRIPTION
**Pull request by es20490446e**
Fixes:
https://bugs.thedarkmod.com/view.php?id=6511

### CODE REVIEW

**Comment by es20490446e** [comment]
@codereader

**Comment by MirceaKitsune** [comment]
Eagerly awaiting the fix myself: I can no longer compile and use DarkRadiant over this issue. I use Manjaro Linux which switched to libgit 1.8 recently, this seems to be the cause with DR requiring a fix to support the newer library. Thank you for the pull request and I hope it can be merged ASAP.

**Comment by es20490446e** [comment]
@MirceaKitsune Use this [recipe](https://gitlab.com/es20490446e/express/-/blob/master/recipes/darkradiant/PKGBUILD?ref_type=heads) changing `pkgver=3.9.0`.

**Comment by MirceaKitsune** [comment]
@es20490446e I got it working for now by looking at your PR: You just need to remove the word `const` at Commit.h line 55 and Repository.cpp line 339 and it works. I did that as a workaround, recompiled, then changed it back in the source code to avoid Git conflicts when this is merged since I shouldn't need to recompile again before then.

**Comment by es20490446e** [comment]
Fixed 👍

**Comment by es20490446e** [comment]
Yeah, it doesn't make much sense to have two cases when you are just using the last libgit2 anyways.

Fixed.

**Comment by MirceaKitsune** [comment]
Looks perfect now! Can confirm it works, hope this can be merged soon.

**Comment by MirceaKitsune** [comment]
Strange: Although this PR was merged and I updated and did a fully clean recompile, I still seem to get the same error. Was part of it missed or the issue added elsewhere since?

```
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/pm_lwo.c: In function ‘_lwo_load’:
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/pm_lwo.c:373:57: warning: ‘PicoFindVertexCombinationInHashTable’ accessing 24 bytes in a region of size 16 [-Wstringop-overflow=]
  373 |                                 vertexCombinationHash = PicoFindVertexCombinationInHashTable( hashTable, xyz, normal, st, color );
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/pm_lwo.c:373:57: note: referencing argument 4 of type ‘double[3]’
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/pm_lwo.c:373:57: note: referencing argument 5 of type ‘picoByte_t[4]’ {aka ‘unsigned char[4]’}
In file included from /home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/picointernal.h:55,
                 from /home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/pm_lwo.c:39:
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/picomodel.h:335:34: note: in a call to function ‘PicoFindVertexCombinationInHashTable’
  335 | picoVertexCombinationHash_t     *PicoFindVertexCombinationInHashTable( picoVertexCombinationHash_t **hashTable, picoVec3_t xyz, picoVec3_t normal, picoVec3_t st, picoColor_t color );
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/pm_lwo.c:383:65: warning: ‘PicoAddVertexCombinationToHashTable’ accessing 24 bytes in a region of size 16 [-Wstringop-overflow=]
  383 |                                         vertexCombinationHash = PicoAddVertexCombinationToHashTable( hashTable, xyz, normal, st, color, (picoIndex_t) numverts );
      |                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/pm_lwo.c:383:65: note: referencing argument 4 of type ‘double[3]’
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/pm_lwo.c:383:65: note: referencing argument 5 of type ‘picoByte_t[4]’ {aka ‘unsigned char[4]’}
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/radiantcore/model/picomodel/lib/picomodel.h:336:30: note: in a call to function ‘PicoAddVertexCombinationToHashTable’
  336 | picoVertexCombinationHash_t *PicoAddVertexCombinationToHashTable( picoVertexCombinationHash_t **hashTable, picoVec3_t xyz, picoVec3_t normal, picoVec3_t st, picoColor_t color, picoIndex_t index );
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MirceaKitsune** [comment]
Strange: Although this PR was merged and I updated and did a fully clean recompile, I still seem to get the same error. Was part of it missed or the issue added elsewhere since?

```
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/plugins/vcs/Repository.cpp: In member function ‘void vcs::git::Repository::createCommit(const vcs::git::CommitMetadata&, const vcs::git::Reference::Ptr&)’:
/home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/plugins/vcs/Repository.cpp:368:49: error: invalid conversion from ‘const git_commit**’ to ‘git_commit* const*’ [-fpermissive]
  368 |         parentCommits.size(), parentCommits.data());
      |                               ~~~~~~~~~~~~~~~~~~^~
      |                                                 |
      |                                                 const git_commit**
In file included from /usr/include/git2/repository.h:14,
                 from /usr/include/git2/annotated_commit.h:11,
                 from /usr/include/git2.h:11,
                 from /home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/plugins/vcs/Reference.h:5,
                 from /home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/plugins/vcs/Repository.h:5,
                 from /home/mircea/Games/Quake/TheDarkMod/DarkRadiant_GIT/plugins/vcs/Repository.cpp:1:
/usr/include/git2/commit.h:369:28: note:   initializing argument 10 of ‘int git_commit_create(git_oid*, git_repository*, const char*, const git_signature*, const git_signature*, const char*, const char*, const git_tree*, size_t, git_commit* const*)’
  369 |         git_commit * const parents[]);
      |         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
make[2]: *** [plugins/vcs/CMakeFiles/vcs.dir/build.make:104: plugins/vcs/CMakeFiles/vcs.dir/Repository.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:613: plugins/vcs/CMakeFiles/vcs.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by es20490446e** [comment]
Let me check, and I will come back.

**Comment by MirceaKitsune** [comment]
Took a closer look and I can only conclude the commit didn't get merged properly for some reason.

https://github.com/codereader/DarkRadiant/blob/master/plugins/vcs/Repository.cpp#L337

While the `plugins/vcs/Commit.h` part is in master, `plugins/vcs/Repository.cpp` still contains the problematic `const` at line 337. The last commit in this PR fixed it so no idea how that might have happened. I deleted it manually in my local checkout and once more DR compiles fine after that, please fix in the repo as well when you have a moment.

**Comment by es20490446e** [comment]
Got reverted at https://github.com/codereader/DarkRadiant/commit/0ccecc0e4c080c31d128ec2909f6a9a4aa1acf62.

@codereader Why?

**Comment by es20490446e** [comment]
Building 3.9.0 is working for me at this time, with libgit2 1.8.1.

**Comment by MirceaKitsune** [comment]
I seem to have libgit2 1:1.8.1-1 myself, but I always use latest DarkRadiant Git master, which on Manjaro still throws errors without that change.

**Comment by MirceaKitsune** [comment]
Any news on this please? To my knowledge the latest DarkRadiant master still can't be compiled on an updated Linux distro without removing that const manually. Maybe you should keep the libgit version #IFDEF check just for the `plugins/vcs/Repository.cpp` change? Curious what @codereader thinks and where the issue lies.

**Pull request merged**
