### PR TITLE
Auto-close the Choose Shader dialog when double-clicking a 'valued' t…

### PR DESCRIPTION
**Pull request by duzenko**
…ree node

https://bugs.thedarkmod.com/view.php?id=5752

### CODE REVIEW

**Comment by duzenko** [comment]
@codereader 
I could be wrong with wx events declaration - do I need to actually subclass event classes? I hope not

**Comment by duzenko** [comment]
Also, formatting? In VS2019 it looks ok but not in diff here
image

**Comment by codereader** [comment]
I'll try to have a look at this soon. The white space style is defined in the .editorconfig file in the repo root - hitting tab inserts 4 spaces.

General coding style is not consistent especially with older code. The current style I've been following over the recent years is to use a newline for the opening braces. No additional whitespace padding in the parenthesed expressions like IF and function calls. That said, I definitely won't reject a contribution just because of syntax styling. Design, readability and maintainability is far more important.

**Comment by codereader** [comment]
I like the approach of adding this to the base wxutil::TreeView type itself, so we could share the behaviour across many client windows. I'd definitely try to avoid the new event declaration, since it overlaps with the existing **wxEVT_DATAVIEW_ITEM_ACTIVATED** (which is also triggered by hitting the Enter key, not just double-clicks). This abstraction makes sense I think, so the reaction to those ITEM_ACTIVATED events should be handled instead of the custom event.

I've been wanting DR to "select & OK" the double-clicked element quite a few times myself, especially when creating entities, so this is a nice addition. I'd definitely like to generalise this behaviour to as many tree selection windows as possible (MediaBrowser, ModelSelector, EntityChooser, SoundChooser, etc.), and some of them are already handling this ITEM_ACTIVATED event in their own custom way.
Can you try to get an overview over these windows and see how we could approach that? I think we won't be able to share much of the actual handling code since these selectors are all reacting differently on clicking OK, but I'd definitely want to try to roll this out to most if not all of the dialogs for consistency.

**Comment by codereader** [comment]
Oh, and a note on the lambda capture: you probably don't need to capture **this** if you are generally capturing everything else by reference, so your lambda could simply begin lile **[&]**.

**Comment by duzenko** [comment]
@codereader 
You can see that I'm rather clueless about wxWidgets
> This abstraction makes sense I think, so the reaction to those ITEM_ACTIVATED events should be handled instead of the custom event.
You mean to catch `wxEVT_DATAVIEW_ITEM_ACTIVATED` in `ShaderChooser`? I tried to `Bind( wxEVT_DATAVIEW_ITEM_ACTIVATED...` but it's not triggering
Am I missing something?

**Comment by codereader** [comment]
> Also, which dialog already closes with double click? MediaBrowser is not a dialog, ModelSelector, EntityChooser, SoundChooser all don't close.
Right, MediaBrowser doesn't close, but it reacts to double-clicks or rather ITEM_ACTIVATED already - which assigns the double-clicked material to the selection.
The rest you mentioned are not selecting & closing on double-click, as you observed, but it would be nice if they do.



> Or just send `wxEVT_DATAVIEW_ITEM_ACTIVATED` instead of `EV_TREE_DOUBLE_CLICK`?
Yes, I think that should work. I think the reason it doesn't propagate, is that the TreeView is catching _ITEM_ACTIVATED_ itself and doesn't call _event.Skip()_. Maybe calling _Skip()_ in the _TreeView::_onItemActivated_ is enough to let it slip through.

**Comment by duzenko** [comment]
@codereader That worked
Should I add handlers for `wxEVT_DATAVIEW_ITEM_ACTIVATED` to other dialogs in the same manner? E.g. lambda vs. new class method?

**Comment by codereader** [comment]
Nice, thanks. I'll edit the issue description to be focused at the ShaderChooser dialog which is now reacting to double-clicks. Feel free to have a look at the other dialogs, that would be a welcome addition for sure!

**Comment by duzenko** [comment]
I did other dialogs as well, will commit over the weekend if have time

**Pull request merged**
