### PR TITLE
Fix bug where cloning an entity using editor_rotatable and an angle key would cause the rotation matrix to be reset by an empty rotation key

### PR DESCRIPTION
**Pull request by chalonverse**
If you have an `"editor_rotatable"` entity but are using the `"angle"` key and not the `"rotation"` key, there is a bug when cloning an entity where the cloned entity has a identity rotation matrix (and thus, it's arrow is wrong). 

Specifically, when executing these two lines of code, you end up where the `m_rotation` first gets set to the correct value for the `"angle"` but then gets set back to default because the `"rotation"` is unset:
https://github.com/codereader/DarkRadiant/blob/b89843f80b4fb7fece62d188bdc1cf78287a450c/radiantcore/entity/generic/GenericEntityNode.cpp#L63-L64

The fix I made here is to add an additional check when cloning a `GenericEntityNode` to make sure we set the angle key if that's what was set on the entity. I confirmed that duplicating then works properly for `"editor_rotatable"` entities regardless of whether they use `"angle"` or `"rotation"`.

This bug doesn't present itself when creating a `GenericEntityNode` in from level file because the keys are then set based on the spawn args, which makes sure it's setup properly.

### CODE REVIEW

**Comment by codereader** [comment]
Thanks for the fix and the pull request. As soon as I can find the time to add a unit test (this kind of behaviour deserves a test), I'll go ahead merge it. Leaving it open, as a reminder for myself.

**Comment by chalonverse** [comment]
Oh yeah, I forgot there were unit tests.

I went ahead and added two new unit tests to the PR in Entity.cpp:
- `CloneGenericEntityRotatableAngle` fails without the bug fix in this PR, and passes with the bug fix
- `CloneGenericEntityRotatableRotation` passes before the bug fix, and continues to pass with the bug fix

I also added in the `"info_vacuumSeparator"` entity def to the test data because it didn't seem like the current set of entities in the test data had a `GenericEntityNode` that was `"editor_rotatable"`.

**Comment by codereader** [comment]
Awesome, that's how it's done!

Thanks a lot, I appreciate the extra effort. It's also nice to see that you seem to know your way around in the DR codebase.

**Comment by chalonverse** [comment]
To be honest, I wouldn’t say I’m that familiar with the DR code haha. But I figure out parts of it as I need to.

If you weren’t aware, we are using the Doom 3 engine on this game: https://store.steampowered.com/app/301280/Skin_Deep/

Our designers have been using DarkRadiant as our level editor, so that’s why I’ve been contributing some changes.

**Comment by codereader** [comment]
It's always awesome to see that DR is used by projects other than TDM!

**Pull request merged**
