### PR TITLE
Fix GenericEntityNode not calculating the direction correctly with "editor_rotatable"

### PR DESCRIPTION
**Pull request by chalonverse**
As you know, the Doom 3 engine uses a convention where +X is forward. In code, if you get the forward vector from the rotation matrix, it will give you the components corresponding to the X axis and call that "forward". Our expectation is that when the level editor shows the direction arrow of an entity, it should also behave this way.

However, if `"editor_rotatable"` is set on the entity (to allow arbitrary 3D rotation), the `m_ray.direction` is being calculated using the Z axis of the rotation matrix rather than the X axis, which seems wrong to me.

You can observe the nonintuitive behavior with the following steps:

1. Have an entity definition that does ***NOT*** have `"editor_rotatable"` set.
2. Place an instance of this entity in a level and set the `"angle"` key to some angle like `1.57` (~90 degrees).
3. View that the direction arrow points in an expected direction (rotated ~90 degrees about the world Z axis)
4. Change the entity definition so it now has `"editor_rotatable"` set
5. Notice that the arrow now points straight up (which, without #33 will appear as a straight line and not an arrow)

Our expectation is that regardless of `"editor_rotatable"` being set or not, the direction arrow should be consistent for the same angle. Furthermore, we think the level editor should maintain the same direction conventions used in the engine.

This PR changes it so even if `"editor_rotatable"` is set, it will calculate the direction matching these expectations.

### CODE REVIEW

**Comment by codereader** [comment]
Thanks for the request!

It's been a long time since I've touched the rotation/direction behaviour, but I seem to recall that using the z-direction was necessary to get particle emitters work correctly. Can you confirm that these are still working as they should? Particles can be configured to respect the entity's direction, which I think was related to this.

As for the code in GenericEntity: it seems the z-direction has been introduced quite some time ago, resolving this issue report: https://bugs.thedarkmod.com/view.php?id=1338

**Comment by chalonverse** [comment]
I’ll investigate the emitters and get back to you.

However, I can understand not wanting to change the default if that’s just the way it’s been for 15 years.

What if I added a new entity def key which can be used to specify we want forward to be X for the editor entity direction? Would that work?

And maybe on top of that, could have a setting in the editor which specifies what the default value is for entity defs which don’t have it set specifically.

**Comment by codereader** [comment]
Thanks in advance for the effort. In cases like this, I usually resort to reading the idTech4 game code to find out what kind of default it is using. If there's a default, DarkRadiant should use that too. If the default is differing between games, it'd be possible to define the default value in the .game files.

**Comment by chalonverse** [comment]
That makes sense. I tested this out a bit in our (Blendo) fork of idTech4, and the results are inconclusive, at least in terms of deciding what is "correct."

- In game, the forward vector for the `idFuncEmitter` entity behaves the way I was expecting it to -- if you use the "angle" key the forward vector is, in fact, on the XY plane (and not just pointing straight up on Z)
- However, the direction the particles travel in does ***NOT*** correlate to the direction of the entity, instead, the particles travel in the direction of the Z-axis of the entity's rotation matrix, which corresponds to the arrow that you have in DarkRadiant
- We've also observed that when spawning an emitter in-game, we have to pitch the emitter 90 degrees downwards for the emitter to emit particles along the forward direction

So I guess the question is, should the direction arrow in DarkRadiant show the direction of the entity's forward vector, or should the direction arrow in DarkRadiant show the direction that the emitters travel in? _Or_ should it be that for emitters we show the direction based on the direction the particles will travel, but for non-emitters we show the forward vector of the entity?

The only other idea I have is maybe we could test what happens in the original DOOM 3 radiant editor, to see how it behaves, but I don't have an install of DOOM 3 lying around so I'm not sure how to test that.

(Also, for reference our code for the `idFuncEmitter` and `idDeclParticle` basically matches what's in base idTech4, with just some small additions, so we didn't change anything with regards to the direction the particles travel in).

In the mean time, I have a working option to allow certain entities to "opt in" to showing the forward vector as the direction of the entity, which I can add to this PR but it depends on what you think is the best course of action.

**Comment by codereader** [comment]
Thanks for investigating.
For me, the arrow in the editor is a visual aid that should help mappers to get what they want. So for particle emitters, this arrow should naturally show the direction the particles are using. If other entity types exist where this arrow is not showing what the entity is doing in-game, then it's worth finding out why these entities are doing that in-game and then decide the best way to carry this over to DR. That basically means finding out whether the idFuncEmitter direction is the exception or the rule.

(For exmple, if we find out that particle systems are the only ones using the z-axis as base direction, then we don't have to use the `IRenderEntity::getDirection()` method to determine the particle emission vector, see ParticleNode.cpp:96)

**Comment by chalonverse** [comment]
So, we tested this out in DoomEdit and we discovered that `func_emitter` is treated differently from any other entity with `editor_rotatable`. Instances of `func_emitter` behave the way DarkRadiant currently does (using the up vector for the direction arrow), but other entities with `editor_rotatable` used the forward.

I dove into the idTech4 source and it turns out that there actually is special case logic to use the up vector ***ONLY*** for `func_emitter` and `func_splat`. Everything else uses forward.

`Brush_DrawFacingAngle` has special case code that says if it's a particle, use the up vector to draw the facing arrow rather than forward:
https://github.com/id-Software/DOOM-3/blob/a9c49da5afb18201d31e3f0a429a037e56ce2b9a/neo/tools/radiant/EditorBrush.cpp#L3556-L3572

The only time `Brush_DrawFacingAngle` is called where `particle` is true is from `Brush_DrawEmitter`:
https://github.com/id-Software/DOOM-3/blob/a9c49da5afb18201d31e3f0a429a037e56ce2b9a/neo/tools/radiant/EditorBrush.cpp#L4253-L4267

`Brush_DrawEmitter` only does something if the `ECLASS_PARTICLE` flag is set for the entity show flags, which is only set for entities of name `func_emitter` or `func_splat`:
https://github.com/id-Software/DOOM-3/blob/a9c49da5afb18201d31e3f0a429a037e56ce2b9a/neo/tools/radiant/ECLASS.CPP#L287-L288

If you check the latest version of the code in the PR branch, I mimicked this behavior. There's a new `_3DdirectionUsesUp` bool that gets set to true only for `func_emitter` or `func_splat`, false otherwise. Then, I changed `updateTransform` to

This seemed like a low impact way to get the behavior to match. Since `GenericEntityNode` is `final`, we can't subclass that, and adding a whole new class that has the identical function of `GenericEntityNode`, except for `updateTransform`, seems like overkill.

**Comment by codereader** [comment]
Very nice find, thank you for doing the footwork and checking out the sources, this is appreciated! Gotta love these little exceptions in the game code.

Checked out the adjusted code, your fix is pretty much what I'd have done myself, so I'm going to merge this right after this comment. I agree that a subclass is not necessary just yet, the single if clause is fine, and the more expensive checks are performed once in the constructor.

(Linked issue: https://bugs.thedarkmod.com/view.php?id=6249)

**Pull request merged**
