### PR TITLE
Fix snapcraft.yaml file

### PR DESCRIPTION
**Pull request by Swizzler121**
I've been working on making the snapcraft.yaml file in the git repository to work (again?) I've got the program compiling and running, but it's throwing some weird errors when you try and open the file browser I'm still trying to understand, but it's definitely a start as before It wasn't compiling at all.

the crash if anyone's curious:
```
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/i
mage-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x1
6/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
zsh: abort (core dumped)  darkradiant
```

### CODE REVIEW

**Comment by Swizzler121** [comment]
I found this, but I tried the fix and it didn't work, so i'm guessing it works differently for snap packages:

https://source.puri.sm/Librem5/OS-issues/-/issues/17

**Comment by Swizzler121** [comment]
Okay it's working now without crashing, i'm just tweaking a few plugs to allow users to access secondary drives and stuff

**Comment by Swizzler121** [comment]
One step forward... and another crash. I got it to load to the interface and detect TheDarkMod, then it promptly crashed. Something is still missing in the snap build...

```
/usr/share/libdrm/amdgpu.ids: No such file or directory
ModuleRegistry: Warning! Module with name ModelSkinCache requested but not found!
SIGSEGV signal caught: 11
0: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/modules/libradiantcore.so(_ZN6applog15SegFaultHandler14_handleSigSegvEi+0x45d) [0x7f75c9f0edcd]
1: /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f75ce476210]
2: /snap/darkradiant/x1/usr/local/bin/darkradiant(+0x414cc5) [0x5636d3760cc5]
3: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/libwxutil.so(_ZN6wxutil16VFSTreePopulator11forEachNodeERNS0_7VisitorE+0x1db) [0x7f75cfd1a94b]
4: /snap/darkradiant/x1/usr/local/bin/darkradiant(+0x416520) [0x5636d3762520]
5: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/libwxutil.so(_ZN6wxutil29ThreadedResourceTreePopulator5EntryEv+0x6b) [0x7f75cfd09cdb]
6: /snap/darkradiant/x1/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0(_ZN8wxThread9CallEntryEv+0xaa) [0x7f75cf94d59a]
7: /snap/darkradiant/x1/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0(+0x1dc0da) [0x7f75cf9590da]
8: /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f75ce62b609]
9: /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f75ce552293]
ModuleRegistry: Warning! Module with name RadiantCore requested but not found!
SIGSEGV signal caught: 11
0: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/modules/libradiantcore.so(_ZN6applog15SegFaultHandler14_handleSigSegvEi+0x45d) [0x7f75c9f0edcd]
1: /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f75ce476210]
2: /snap/darkradiant/x1/usr/local/bin/darkradiant(+0x16b0b5) [0x5636d34b70b5]
3: /snap/darkradiant/x1/usr/local/bin/darkradiant(+0x16b79d) [0x5636d34b779d]
4: /snap/darkradiant/x1/usr/local/bin/darkradiant(+0x3122bc) [0x5636d365e2bc]
5: /snap/darkradiant/x1/usr/local/bin/darkradiant(+0x31d540) [0x5636d3669540]
6: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/modules/libradiantcore.so(_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_St10shared_ptrI18RegisterableModuleEESt10_Select1stISB_ESt4lessIS5_ESaISB_EE8_M_eraseEPSt13_Rb_tree_nodeISB_E+0x11d) [0x7f75ca077cdd]
7: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/modules/libradiantcore.so(_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_St10shared_ptrI18RegisterableModuleEESt10_Select1stISB_ESt4lessIS5_ESaISB_EE8_M_eraseEPSt13_Rb_tree_nodeISB_E+0x27) [0x7f75ca077be7]
8: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/modules/libradiantcore.so(_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_St10shared_ptrI18RegisterableModuleEESt10_Select1stISB_ESt4lessIS5_ESaISB_EE8_M_eraseEPSt13_Rb_tree_nodeISB_E+0x27) [0x7f75ca077be7]
9: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/modules/libradiantcore.so(_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_St10shared_ptrI18RegisterableModuleEESt10_Select1stISB_ESt4lessIS5_ESaISB_EE8_M_eraseEPSt13_Rb_tree_nodeISB_E+0x27) [0x7f75ca077be7]
10: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/modules/libradiantcore.so(_ZN6module14ModuleRegistry13unloadModulesEv+0xd1) [0x7f75ca075a41]
11: /snap/darkradiant/x1/usr/local/bin/../lib/darkradiant/modules/libradiantcore.so(_ZN6module14ModuleRegistry15shutdownModulesEv+0xa2) [0x7f75ca075ba2]
12: /snap/darkradiant/x1/usr/local/bin/darkradiant(+0x1de74b) [0x5636d352a74b]
13: /snap/darkradiant/x1/usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0(_Z7wxEntryRiPPw+0x5d) [0x7f75cf89074d]
14: /snap/darkradiant/x1/usr/local/bin/darkradiant(+0x14de52) [0x5636d3499e52]
15: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f75ce4570b3]
16: /snap/darkradiant/x1/usr/local/bin/darkradiant(+0x15c6ce) [0x5636d34a86ce]
ModuleRegistry: Warning! Module with name EventManager requested but not found!
zsh: segmentation fault (core dumped)  darkradiant
```

**Comment by codereader** [comment]
Snap file has been removed from the repo lately.

**Pull request closed without merging**
